version: "3.9"
services:
  task:
    build:
      context: ./
    ports:
      - 6003:13003
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
